/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false functions/worker-configuration.d.ts` (hash: fea4abaead918de4d8457e082847280a)
interface __BaseEnv_Env {
	SEARCH_RATE_LIMIT_DB: D1Database;
	AI: Ai;
	SKIN_MAKER_ENABLED: "false" | "true";
	SKIN_AI_MODEL: "gpt-6-luna";
	SKIN_TURNSTILE_SITE_KEY: "" | "0x4AAAAAAErIZJD3i5QFG2LB";
	SEARCH_EMBEDDING_MODEL: "@cf/baai/bge-m3";
	SEARCH_EMBEDDING_DIMENSIONS: "1024";
	WIKI_SEARCH_ENABLED: "false" | "true";
	WIKI_SEARCH_MIN_SCORE: "0.40";
	PORTAL_SEARCH_ENABLED: "false" | "true";
	PORTAL_SEARCH_MIN_SCORE: "0.50";
	ACECORE_SEARCH_ENABLED: "false" | "true";
	ACECORE_SEARCH_MIN_SCORE: "0.50";
	SCHOOLS_SEARCH_ENABLED: "false" | "true";
	SCHOOLS_SEARCH_MIN_SCORE: "0.50";
	SYSTEMS_SEARCH_ENABLED: "false" | "true";
	SYSTEMS_SEARCH_MIN_SCORE: "0.50";
	WORLD_FOUNDATION_SEARCH_ENABLED: "false" | "true";
	WORLD_FOUNDATION_SEARCH_MIN_SCORE: "0.40";
	CMS_GITHUB_APP_CLIENT_ID: string;
	CMS_GITHUB_APP_CLIENT_SECRET: string;
	CMS_GITHUB_APP_INSTALLATION_ID: string;
	CMS_OAUTH_STATE_SECRET: string;
	CMS_AI: Fetcher /* cms-ai */;
	WIKI_SEARCH_INDEX?: VectorizeIndex;
	PORTAL_SEARCH_INDEX?: VectorizeIndex;
	ACECORE_SEARCH_INDEX?: VectorizeIndex;
	SCHOOLS_SEARCH_INDEX?: VectorizeIndex;
	SYSTEMS_SEARCH_INDEX?: VectorizeIndex;
	WORLD_FOUNDATION_SEARCH_INDEX?: VectorizeIndex;
	CMS_ACCESS_AUD?: "3c891371aa539493f09b2030c67d9d7c42011ce274b2aa42fdad0ad90e809265";
	CMS_ACCESS_TEAM_DOMAIN?: "https://acecore.cloudflareaccess.com";
	CMS_ACCESS_HOSTNAMES?: "asv.acecore.net";
	CMS_GITHUB_TOKEN_ISSUER?: Fetcher /* aceserver-portal-cms-token-issuer */;
	ALPHA_CHAT_SERVICE?: Fetcher /* aceserver-alpha-chat-production */;
	SKIN_OPENAI_SERVICE?: Fetcher /* aceserver-portal-skin-openai */;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		SEARCH_RATE_LIMIT_DB: D1Database;
		AI: Ai;
		SKIN_MAKER_ENABLED: "false";
		SKIN_AI_MODEL: "gpt-6-luna";
		SKIN_TURNSTILE_SITE_KEY: "";
		SEARCH_EMBEDDING_MODEL: "@cf/baai/bge-m3";
		SEARCH_EMBEDDING_DIMENSIONS: "1024";
		WIKI_SEARCH_ENABLED: "false";
		WIKI_SEARCH_MIN_SCORE: "0.40";
		PORTAL_SEARCH_ENABLED: "false";
		PORTAL_SEARCH_MIN_SCORE: "0.50";
		ACECORE_SEARCH_ENABLED: "false";
		ACECORE_SEARCH_MIN_SCORE: "0.50";
		SCHOOLS_SEARCH_ENABLED: "false";
		SCHOOLS_SEARCH_MIN_SCORE: "0.50";
		SYSTEMS_SEARCH_ENABLED: "false";
		SYSTEMS_SEARCH_MIN_SCORE: "0.50";
		WORLD_FOUNDATION_SEARCH_ENABLED: "false";
		WORLD_FOUNDATION_SEARCH_MIN_SCORE: "0.40";
		CMS_GITHUB_APP_CLIENT_ID: string;
		CMS_GITHUB_APP_CLIENT_SECRET: string;
		CMS_GITHUB_APP_INSTALLATION_ID: string;
		CMS_OAUTH_STATE_SECRET: string;
		CMS_AI: Fetcher /* cms-ai */;
	}
	interface ProductionEnv {
		SEARCH_RATE_LIMIT_DB: D1Database;
		WIKI_SEARCH_INDEX: VectorizeIndex;
		PORTAL_SEARCH_INDEX: VectorizeIndex;
		ACECORE_SEARCH_INDEX: VectorizeIndex;
		SCHOOLS_SEARCH_INDEX: VectorizeIndex;
		SYSTEMS_SEARCH_INDEX: VectorizeIndex;
		WORLD_FOUNDATION_SEARCH_INDEX: VectorizeIndex;
		AI: Ai;
		SKIN_MAKER_ENABLED: "true";
		SKIN_AI_MODEL: "gpt-6-luna";
		CMS_ACCESS_AUD: "3c891371aa539493f09b2030c67d9d7c42011ce274b2aa42fdad0ad90e809265";
		CMS_ACCESS_TEAM_DOMAIN: "https://acecore.cloudflareaccess.com";
		CMS_ACCESS_HOSTNAMES: "asv.acecore.net";
		SKIN_TURNSTILE_SITE_KEY: "0x4AAAAAAErIZJD3i5QFG2LB";
		SEARCH_EMBEDDING_MODEL: "@cf/baai/bge-m3";
		SEARCH_EMBEDDING_DIMENSIONS: "1024";
		WIKI_SEARCH_ENABLED: "true";
		WIKI_SEARCH_MIN_SCORE: "0.40";
		PORTAL_SEARCH_ENABLED: "true";
		PORTAL_SEARCH_MIN_SCORE: "0.50";
		ACECORE_SEARCH_ENABLED: "true";
		ACECORE_SEARCH_MIN_SCORE: "0.50";
		SCHOOLS_SEARCH_ENABLED: "true";
		SCHOOLS_SEARCH_MIN_SCORE: "0.50";
		SYSTEMS_SEARCH_ENABLED: "true";
		SYSTEMS_SEARCH_MIN_SCORE: "0.50";
		WORLD_FOUNDATION_SEARCH_ENABLED: "true";
		WORLD_FOUNDATION_SEARCH_MIN_SCORE: "0.40";
		CMS_GITHUB_APP_CLIENT_ID: string;
		CMS_GITHUB_APP_CLIENT_SECRET: string;
		CMS_GITHUB_APP_INSTALLATION_ID: string;
		CMS_OAUTH_STATE_SECRET: string;
		CMS_GITHUB_TOKEN_ISSUER: Fetcher /* aceserver-portal-cms-token-issuer */;
		CMS_AI: Fetcher /* cms-ai */;
		ALPHA_CHAT_SERVICE: Fetcher /* aceserver-alpha-chat-production */;
		SKIN_OPENAI_SERVICE: Fetcher /* aceserver-portal-skin-openai */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SKIN_MAKER_ENABLED" | "SKIN_AI_MODEL" | "SKIN_TURNSTILE_SITE_KEY" | "SEARCH_EMBEDDING_MODEL" | "SEARCH_EMBEDDING_DIMENSIONS" | "WIKI_SEARCH_ENABLED" | "WIKI_SEARCH_MIN_SCORE" | "PORTAL_SEARCH_ENABLED" | "PORTAL_SEARCH_MIN_SCORE" | "ACECORE_SEARCH_ENABLED" | "ACECORE_SEARCH_MIN_SCORE" | "SCHOOLS_SEARCH_ENABLED" | "SCHOOLS_SEARCH_MIN_SCORE" | "SYSTEMS_SEARCH_ENABLED" | "SYSTEMS_SEARCH_MIN_SCORE" | "WORLD_FOUNDATION_SEARCH_ENABLED" | "WORLD_FOUNDATION_SEARCH_MIN_SCORE" | "CMS_GITHUB_APP_CLIENT_ID" | "CMS_GITHUB_APP_CLIENT_SECRET" | "CMS_GITHUB_APP_INSTALLATION_ID" | "CMS_OAUTH_STATE_SECRET" | "CMS_ACCESS_AUD" | "CMS_ACCESS_TEAM_DOMAIN" | "CMS_ACCESS_HOSTNAMES">> {}
}
