/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/dynmap-r2-cache/wrangler.jsonc --include-runtime=false cloudflare/dynmap-r2-cache/worker-configuration.d.ts` (hash: f76f8ec093c940a26ee0bc74921e2581)
interface __BaseEnv_Env {
	MAIN_BUCKET: R2Bucket;
	SIGEN_BUCKET: R2Bucket;
	RPG_BUCKET: R2Bucket;
	LOBBY_BUCKET: R2Bucket;
	RPG_SUB_BUCKET: R2Bucket;
	SEASON_A_BUCKET: R2Bucket;
	SEASON_A_C_BUCKET: R2Bucket;
	EVENT_BUCKET: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
