/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/cms-token-issuer/wrangler.jsonc --include-runtime=false --env-interface=TokenIssuerEnv cloudflare/cms-token-issuer/worker-configuration.d.ts` (hash: 57792fa67a9e1c739e9cab1861d386fd)
interface __BaseEnv_TokenIssuerEnv {
	CMS_GITHUB_APP_CLIENT_ID: "Iv23lipbsaRsxzUGXHOP";
	CMS_GITHUB_APP_INSTALLATION_ID: "149706696";
	CMS_GITHUB_APP_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_TokenIssuerEnv {}
}
interface TokenIssuerEnv extends __BaseEnv_TokenIssuerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CMS_GITHUB_APP_CLIENT_ID" | "CMS_GITHUB_APP_INSTALLATION_ID" | "CMS_GITHUB_APP_PRIVATE_KEY">> {}
}
